### ISSUE TITLE
페이스북에 공유할 때 질문 제목이 나오면 더 좋을 듯

### ISSUE THREAD

**Issue by smartbos** [ModernPUG/qna#1]
<img width="542" alt="2016-02-07 12 08 22" src="https://cloud.githubusercontent.com/assets/6157033/12870681/aade74dc-cd93-11e5-929c-4a92158c27da.png">

제목 대신 ModernPUG 라고 나와서 아쉬워용~

**Comment by koojunho** [comment]
https://github.com/ModernPUG/modernpug.org/commit/1da0c22b608f8ef9705106eb8945186fe5747317

위에서 고쳤습니다~
