### ISSUE TITLE
내 질문에 답변이 달리면 이메일로 알림이 오면 좋을 듯 합니다.

### ISSUE THREAD

**Issue by smartbos** [ModernPUG/qna#2]

**Comment by koojunho** [comment]
기존에 메일을 보내는 시스템이 있으셨나요?(slack invite 라던지..)

**Comment by smartbos** [comment]
슬랙 초대는 그냥 라라벨의 메일 발송 기능을 썼던거 같아요.

2016년 2월 7일 일요일, Koo Jun Ho<notifications@github.com>님이 작성한 메시지:

> 기존에 메일을 보내는 시스템이 있으셨나요?(slack invite 라던지..)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ModernPUG/qna/issues/2#issuecomment-180977588>.
>


-- 
이현석, Hyunseok Lee, 李炫錫
+82-10-2956-3707
Blog - *http://leehyunseok.com <http://leehyunseok.com>*
Linkedin - http://kr.linkedin.com/pub/hyun-seok-lee/62/632/a58/

앱을 개발하지 않고 무료로 스마트폰으로 푸시 알림을 보낼 수 있습니다. *pushwing.com*
<http://www.pushwing.com/>
Find problems worth solving and co-founder at *startupwithwhy.com
<http://startupwithwhy.com/>*

**Comment by koojunho** [comment]
ModernPUG 위키쪽에 기록하고 닫음.
